<?php

/**
 * @file
 * Line Item module for the Budget System.
 */
function budgetsys_line_entity_info_alter(&$entity_info) {
  foreach (budgetsys_line_item_types() as $type => $info) {
    $entity_info['budgetsys_line_type']['bundles'][$type] = array(
      'admin' => array(
        'path' => 'admin/structure/budget/line/manage/%budgetsys_line_type',
        'real path' => 'admin/structure/budget/line/manage/' . $type,
        'bundle argument' => 5,
      ),
    );
  }
     // Enable the entity API's admin UI.
   $entity_info['budgetsys_line_type']['admin ui'] = array(
      'path' => 'admin/structure/budget/line',
      'file' => 'budgetsys_line.admin.inc',
      'controller class' => 'LineItemTypeUIController',
    );
}    
/**
 * Implements hook_menu().
 */
function budgetsys_line_menu() {
  $items['budget/line/add'] = array(
    'title' => 'Add Budget Line Item',
    'page callback' => 'budgetsys_line_admin_add_page',
    'access arguments' => array('administer budget line items'),
    'file' => 'budgetsys_line.admin.inc',
    'type' => MENU_NORMAL_ITEM,

  );
  $budget_line_uri = 'budget/line/%budgetsys_line';
  $budget_line_uri_argument_position = 2;
  
  $items[$budget_line_uri] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('budgetsys_line', $budget_line_uri_argument_position),
    'page callback' => 'budgetsys_line_page_view',
    'page arguments' => array($budget_line_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'budgetsys_line', $budget_line_uri_argument_position),
    'file' => 'budgetsys_line.pages.inc',
  );
  
  $items[$budget_line_uri . '/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items[$budget_line_uri . '/budget-line'] = array(
    'title' => 'Budget Line',
    'page callback' => 'budgetsys_line_budget_view',
    'page arguments' => array($budget_line_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'budgetsys_line', $budget_line_uri_argument_position),
    'file' => 'budgetsys_line.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );  
  $items[$budget_line_uri . '/delete'] = array(
    'title' => 'Delete task',
    'title callback' => 'budgetsys_line_label',
    'title arguments' => array($budget_line_uri_argument_position),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('budgetsys_line_delete_form', $budget_line_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'budgetsys_line', $budget_line_uri_argument_position),
    'file' => 'budgetsys_line.admin.inc',
  );
  
  $items[$budget_line_uri . '/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('budgetsys_line_item_form', $budget_line_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'budgetsys_line', $budget_line_uri_argument_position),
    'file' => 'budgetsys_line.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  
  foreach (budgetsys_line_item_types() as $type => $info) {
    $items['budget/line/add/' . $type] = array(
      'title' => 'Add ' . entity_label('budgetsys_line_type', $info) . ' Line',
      'page callback' => 'budgetsys_line_add',
      'page arguments' => array(3),
      'access callback' => 'entity_access',
      'access arguments' => array('create', 'budgetsys_line_type', $type),
      'file' => 'budgetsys_line.admin.inc',
    );
  }

  $items['admin/structure/budget/line/%budgetsys_line_type/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('budgetsys_line_type_form_delete_confirm', 4),
    'access arguments' => array('administer budget line items'),
    'weight' => 1,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'budgetsys_line.admin.inc',
  );
  
  
  $items['budget/line/account_number_autocomplete_callback'] = array(
    'page callback' => 'budgetsys_line_account_number_autocomplete_callback',
    'file' => 'budgetsys_line.pages.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('view line items'),
  );
  return $items;
}


/**
 * Adds the theme specifications to the Theme Registry
 */
function budgetsys_line_theme($existing, $type, $theme, $path) {
  return array(
    'budgetsys_line' => array(
      'variables' => array('element' => null),
      'template' => 'budgetsys_line',
      'path' => drupal_get_path('module', 'budgetsys_line') . "/templates",
    ),
    'budgetsys_line_budget' => array(
      'variables' => array('element' => null),
      'template' => 'budgetsys_line_budget',
      'path' => drupal_get_path('module', 'budgetsys_line') . "/templates",
    ),
  );
}

/**
 * Adding Autocomplete for the budget value form
 */
function budgetsys_line_form_budgetsys_value_form_alter(&$form, &$form_state, $form_id) {
 // Adding the oid field to the line item form.
  $value = $form_state['value'];
  module_load_include('inc', 'budgetsys_org', 'budgetsys_org.api');
  $form['account_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Account Number'),
    '#default_value' => $value->account_number,
    '#required' => TRUE,

    '#weight' => -2,
    '#autocomplete_path' => 'budget/line/account_number_autocomplete_callback',
  );

}
