<?php

/**
 * @file
 * Organization module for the Budget System.
 */
function budgetsys_org_entity_info_alter(&$entity_info) {
  $entity_info['budgetsys_org']['bundles']['budgetsys_org'] = array(
      'label' => t('Organization'),
      'admin' => array(
        'path' => 'admin/structure/budget/organization',
        'access arguments' => array('administer budget organizations'),
      ),
    );
     // Enable the entity API's admin UI.
/*   $entity_info['budgetsys_org']['admin ui'] = array(
      'path' => 'admin/structure/budget/organization',
      'file' => 'budgetsys_org.admin.inc',
      'controller class' => 'BudgetsysOrgUIController',
    );
*/ 
}    
 
 
/**
 * Implements hook_menu()
 */
function budgetsys_org_menu() {
  $items = array();
  $items['budget/org/example'] = array(
    'title' => 'Example',
    'page callback' => 'budgetsys_org_example',
    'access arguments' => array('view content'),
    'file' => 'budgetsys_org.pages.inc',
  );
  $items['budget/org/add'] = array(
    'title' => 'Add new organization',
    'page callback' => 'budgetsys_org_add',
    'access arguments' => array('create budget system organizations'),
    'weight' => 2,
    'menu_name' => 'management',
    'file' => 'budgetsys_org.pages.inc',
  );
    $items['budget/org/%budgetsys_org'] = array(
    'title callback' => 'budgetsys_org_page_title',
    'title arguments' => array(2),
    'page callback' => 'budgetsys_org_page_view',
    'page arguments' => array(2),
    'access arguments' => array('view budget organizations'),
    'type' => MENU_CALLBACK,
    'file' => 'budgetsys_org.pages.inc',
  );
  $items['budget/org/%budgetsys_org/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['budget/org/%budgetsys_org/budget'] = array(
    'title' => 'Budget',
    'page callback' => 'budgetsys_org_budget_view',
    'page arguments' => array(2),
    'access arguments' => array('view budget organizations'),
    'file' => 'budgetsys_org.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
    $items['budget/org/%budgetsys_org/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'budgetsys_org_page_edit',
    'page arguments' => array(2),
    'access arguments' => array('update budget organizations'),
    'weight' => 0,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'budgetsys_org.pages.inc',
  );
    $items['budget/org/%budgetsys_org/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('budgetsys_org_delete_confirm', 2),
    'access arguments' => array('delete budget organizations'),
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'file' => 'budgetsys_org.pages.inc',
  );
  $items['admin/structure/budget/organization'] = array(
    'title' => 'Organization settings',
    'description' => 'Configure the settings for the Budget System Organizations.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('budgetsys_org_admin_settings'),
    'access arguments' => array('administer budget organizations'),
    'file' => 'budgetsys_org.admin.inc',
    'weight' => -10,
  );
  $items['admin/structure/budget/organization/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['budget/full/organization'] = array(
    'title' => 'By Organization',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'budgetsys_org_view_budget_organization',
    'access arguments' => array('view content'),
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'budgetsys_org.pages.inc',
  );
  $items['budget/full/category'] = array(
    'title' => 'By Category',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'budgetsys_org_view_budget_category_organization',
    'access arguments' => array('view content'),
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'budgetsys_org.pages.inc',
  );
  return $items;
}

/**
 * Adding the Organization ID for the Line Item Form
 */
function budgetsys_org_form_budgetsys_line_item_form_alter(&$form, &$form_state, $form_id) {
 // Adding the oid field to the line item form.
  $line_item = $form_state['line_item'];
  module_load_include('inc', 'budgetsys_org', 'budgetsys_org.api');
    $form['oid'] = array(
    '#type' => 'select',
    '#title' => t('Organization'),
    '#default_value' => $line_item->oid,
    '#options' => budgetsys_org_organization_select_list(),  
    '#required' => TRUE,
  );
}

/**
 * Adding the Organization ID for the Budget Form
 */
function budgetsys_org_form_budgetsys_value_form_alter(&$form, &$form_state, $form_id) {
 // Adding the oid field to the line item form.
  $value = $form_state['value'];
  module_load_include('inc', 'budgetsys_org', 'budgetsys_org.api');
    $form['oid'] = array(
    '#type' => 'select',
    '#title' => t('Organization'),
    '#default_value' => $value->oid,
    '#options' => budgetsys_org_organization_select_list(),  
    '#required' => TRUE,
    '#weight' => -2,
  );
}
/**
 * Implements hook_budgetsys_value_update
 * Used to calculate and save the budget total.
 */
function budgetsys_org_budgetsys_value_update($value) {
  $oid = $value->oid;
  $organization =budgetsys_org_load($oid);
  $type = $value->type;
  $year = $value->year;
  budgetsys_org_total($organization, $year, $type);
  watchdog('Budget System Organization','Budget Total for %year of the value type %type has been saved for %organization', array('%year' => $year, '%type' => $type, '%organization' => $organization->title));
  return ;
}

/**
 * Adds the theme specifications to the Theme Registry
 */
function budgetsys_org_theme($existing, $type, $theme, $path) {
  return array(
    'budgetsys_org' => array(
      'variables' => array('element' => null),
      'template' => 'budgetsys_org',
      'path' => drupal_get_path('module', 'budgetsys_org') . "/templates",
    ),
    'budgetsys_org_budget' => array(
      'variables' => array('element' => null),
      'template' => 'budgetsys_org_budget',
      'path' => drupal_get_path('module', 'budgetsys_org') . '/templates',
    ),
    'budgetsys_full_budget_organizations' => array(
      'variables' => array('element' => null),
      'template' => 'budgetsys_full_budget_organizations',
      'path' => drupal_get_path('module','budgetsys_org') . '/templates',      
    ),
    'budgetsys_full_budget_category_organizations' => array(
      'variables' => array('element' => null),
      'template' => 'budgetsys_full_budget_category_organizations',
      'path' => drupal_get_path('module','budgetsys_org') . '/templates',      
    ),
  );
}