<?php

/**
 * @file 
 * The main module file for the Budget System Value.
 */

/**
* Implements hook_entity_info_alter().
*/
function budgetsys_value_entity_info_alter(&$entity_info) {
  foreach (budgetsys_value_types() as $type => $info) {
    $entity_info['budgetsys_value']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/budget/value/manage/%budgetsys_value_type',
        'real path' => 'admin/structure/budget/value/manage/' . $type,
        'bundle argument' => 5,
      ),
    );
  }
}

/**
 * Implements hook_menu().
 */
function budgetsys_value_menu() {
    $items['budget/value/example'] = array(
      'title' => 'Testing page',
      'page callback' => 'budgetsys_value_example_page',
      'access arguments' => array('view content'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'budgetsys_value.pages.inc',
    );
    $items['budget/value/add'] = array(
    'title' => 'Add Budget Value',
    'page callback' => 'budgetsys_value_admin_add_page',
    'access arguments' => array('administer budget values'),
    'file' => 'budgetsys_value.admin.inc',
    'type' => MENU_NORMAL_ITEM,

  );
  $budget_value_uri = 'budget/value/%budgetsys_value';
  $budget_value_uri_argument_position = 2;
  
  $items[$budget_value_uri] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('budgetsys_value', $budget_value_uri_argument_position),
    'page callback' => 'budgetsys_value_page_view',
    'page arguments' => array($budget_value_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'budgetsys_value', $budget_value_uri_argument_position),
    'file' => 'budgetsys_value.pages.inc',
  );
  
  $items[$budget_value_uri . '/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items[$budget_value_uri . '/delete'] = array(
    'title' => 'Delete Value',
    'title callback' => 'budgetsys_value_label',
    'title arguments' => array($budget_value_uri_argument_position),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('budgetsys_value_delete_form', $budget_value_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'budgetsys_value', $budget_value_uri_argument_position),
    'file' => 'budgetsys_value.pages.inc',
  );
  
  $items[$budget_value_uri . '/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('budgetsys_value_form', $budget_value_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'budgetsys_value', $budget_value_uri_argument_position),
    'file' => 'budgetsys_value.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  
  foreach (budgetsys_value_types() as $type => $info) {
    $items['budget/value/add/' . $type] = array(
      'title' => 'Add ' . entity_label('budgetsys_value_type', $info) . ' Value',
      'page callback' => 'budgetsys_value_add',
      'page arguments' => array(3),
      'access callback' => 'entity_access',
      'access arguments' => array('create', 'budgetsys_value_type', $type),
      'file' => 'budgetsys_value.pages.inc',
    );
  }

  $items['admin/structure/budget/value/%budgetsys_value_type/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('budgetsys_value_type_form_delete_confirm', 4),
    'access arguments' => array('administer budget value items'),
    'weight' => 1,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'budgetsys_value.admin.inc',
  );
  
  $items['admin/config/system/budget_system_value'] = array(
    'title' => t('Budget System Value Configuration'),
    'description' => 'Configuration for the Budget System Value module',
    'page callback' => 'drupal_get_form',
    'page arguments' =>array('budgetsys_value_configuration_form'),
    'access arguments' => array('administer budget system'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'budgetsys_value.settings.inc',
  );
  return $items;
}


/**
  * Implements hook_views_api().
  */
function budgetsys_value_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'budgetsys_value'),
  );
}

/**
 * Adds the theme specifications to the Theme Registry
 */
function budgetsys_value_theme($existing, $type, $theme, $path) {
  return array(
    'budgetsys_value' => array(
      'variables' => array('element' => null),
      'template' => 'budget_value',
      'path' => drupal_get_path('module', 'budgetsys_value') . "/templates",
    ),
  );
}